// Volunteer opportunities data — Buncombe County, NC
// Arden, NC reference point: 35.4734, -82.5151
//
// soloStatus values (CRITICAL — surfaced in every view):
//   "verified"   = Posted policy explicitly allows solo 15-year-old
//   "verify"     = Age not posted publicly — MUST call to confirm
//   "posted-16"  = Posted minimum age is 16; ask if a waiver/exception is possible

window.ARDEN = { lat: 35.4734, lng: -82.5151 };

window.OPPORTUNITIES = [
  {
    id: "america-cares-arden",
    name: "America Cares — Disaster Relief Warehouse",
    tier: 2,
    fit: "Only formal opportunity physically in Arden",
    category: "Disaster Relief",
    categoryColor: "warning",
    ages: "16+ (posted)",
    minAge: 16,
    soloStatus: "posted-16",
    soloNote: "Listed minimum age is 16. Worth asking if a waiver is possible for 15 — they accept any time block and operate 7 days a week.",
    askAbout: true,
    parentRequired: false,
    address: "Suite 40, 309 Rockwood Rd, Arden, NC 28704",
    lat: 35.4773,
    lng: -82.5258,
    distanceMi: 0.5,
    phone: null,
    email: null,
    website: "https://www.handsonasheville.org/need/detail/?need_id=1010261",
    orgWebsite: "https://americacares.net",
    apply: "Sign up via Hands On Asheville listing",
    schedule: "7 days/week, 9:30am–5pm; any time block welcome",
    notes: "Sort and distribute disaster relief supplies."
  },
  {
    id: "skyland-library",
    name: "Skyland / South Buncombe Library",
    tier: 1,
    fit: "Closest library to Arden",
    category: "Library",
    categoryColor: "blue",
    ages: "Not posted",
    minAge: null,
    soloStatus: "verify",
    soloNote: "Age policy is not posted online. Call the branch directly to confirm whether a 15-year-old can volunteer solo.",
    askAbout: true,
    parentRequired: false,
    address: "260 Overlook Road, Asheville, NC 28803",
    lat: 35.5060,
    lng: -82.5181,
    distanceMi: 3,
    phone: "(828) 250-6488",
    email: null,
    website: "https://www.buncombenc.gov/289/Skyland-South-Buncombe",
    apply: "Call branch to ask about teen volunteer/programs help",
    schedule: "Tue 10am–8pm · Wed–Fri 10am–6pm · Sat 10am–5pm",
    notes: "Shelving, summer reading, program help."
  },
  {
    id: "ymca-leaders-club-reuter",
    name: "YMCA Leaders Club — Reuter Family YMCA",
    tier: 1,
    fit: "Closest large teen program to Arden",
    category: "Leadership",
    categoryColor: "primary",
    ages: "12–17 (grades 6–12)",
    minAge: 12,
    soloStatus: "verified",
    soloNote: "Verified: program is explicitly designed for ages 12–17 to volunteer without a parent.",
    askAbout: false,
    parentRequired: false,
    address: "3 Town Square Blvd, Biltmore Park, Asheville, NC 28803",
    lat: 35.4471,
    lng: -82.5366,
    distanceMi: 4,
    phone: "(828) 651-9622",
    phoneAlt: "(828) 684-9620",
    email: "mmichael@ymcawnc.org",
    contactPerson: "Mary Michael",
    website: "https://www.ymcawnc.org/leaders-club",
    apply: "Contact YMCA directly to enroll",
    schedule: "Thursdays 10:00–11:30am OR 5:30–7:00pm",
    notes: "Free, year-long leadership + service program."
  },
  {
    id: "nc-arboretum-explorecorps",
    name: "NC Arboretum EXPLOREcorps",
    tier: 2,
    fit: "Rising grades 9–12; $250 fee; deadline Mar 29",
    category: "Environmental",
    categoryColor: "success",
    ages: "Rising grades 9–12",
    minAge: 14,
    soloStatus: "verified",
    soloNote: "Verified: program is for high-school-aged participants (rising 9–12); participants must have reliable transportation to the Arboretum — i.e. solo attendance is expected.",
    askAbout: false,
    parentRequired: false,
    address: "100 Frederick Law Olmsted Way, Asheville, NC 28806",
    lat: 35.5025,
    lng: -82.6011,
    distanceMi: 9,
    phone: "(828) 665-2492 x333",
    email: "youtheducation@ncarboretum.org",
    contactPerson: "Sarah Gleason",
    website: "https://www.ncarboretum.org/education-programs/explorecorps-volunteer-program/",
    apply: "Applications rolling Dec 17 – Mar 29; reference letter required",
    schedule: "Min 2 weeks Mon–Fri at Discovery Camp",
    notes: "$250 fee (scholarships available)."
  },
  {
    id: "mission-hospital-junior",
    name: "Mission Hospital Junior Volunteer Program",
    tier: 1,
    fit: "Best structured solo program for ages 14+",
    category: "Healthcare",
    categoryColor: "error",
    ages: "14–18",
    minAge: 14,
    soloStatus: "verified",
    soloNote: "Verified: program is explicitly for students 14–18. Parents attend a one-time info session but the teen volunteers solo.",
    askAbout: false,
    parentRequired: false,
    address: "509 Biltmore Avenue, Asheville, NC 28801",
    lat: 35.5779,
    lng: -82.5497,
    distanceMi: 10,
    phone: "(828) 213-1055",
    phoneAlt: "(828) 213-1058",
    email: null,
    website: "https://www.missionhealth.org/locations/mission-hospital/about-us/volunteers",
    apply: "Apply Feb 1–Mar 6 (annual); references by Mar 20; interviews Mar 9–31",
    schedule: "Summer: Jul 6–30, Mon/Wed or Tue/Thu, 9am–3pm",
    notes: "Competitive — ~13 students accepted/year."
  },
  {
    id: "children-first-cis",
    name: "Children First / Communities In Schools",
    tier: 2,
    fit: "After-school tutoring",
    category: "Education",
    categoryColor: "purple",
    ages: "Not posted",
    minAge: null,
    soloStatus: "verify",
    soloNote: "Minimum age is not posted. Email or call to confirm whether a 15-year-old tutor is eligible. Background check is required for all direct-contact volunteers.",
    askAbout: true,
    parentRequired: false,
    address: "50 S. French Broad Ave Ste 246, Asheville, NC 28801",
    lat: 35.5921,
    lng: -82.5573,
    distanceMi: 11,
    phone: "(828) 259-9717",
    email: "info@childrenfirstbc.org",
    website: "https://www.childrenfirstcisbc.org/volunteer",
    apply: "Email to inquire; background check + orientation",
    schedule: "Semester commitment (after-school)",
    notes: "Tutor a child in math or reading."
  },
  {
    id: "asheville-greenworks",
    name: "Asheville GreenWorks",
    tier: 2,
    fit: "Event-based (tree plantings, river cleanups)",
    category: "Environmental",
    categoryColor: "success",
    ages: "Varies by event",
    minAge: null,
    soloStatus: "verify",
    soloNote: "Each event has its own age rule. Check the specific event listing or call before signing up to confirm a solo 15-year-old can attend.",
    askAbout: true,
    parentRequired: false,
    address: "2 Sulphur Springs Road, Asheville, NC 28806",
    lat: 35.5783,
    lng: -82.6017,
    distanceMi: 11,
    phone: "(828) 254-1776",
    email: null,
    website: "https://www.ashevillegreenworks.org",
    apply: "Browse events, sign up online",
    schedule: "Event-based, often weekends",
    notes: "Tree planting, river cleanups, pollinator gardens."
  },
  {
    id: "buncombe-teen-court",
    name: "Buncombe County Teen Court",
    tier: 1,
    fit: "Civic + prestigious; year-round",
    category: "Civic / Legal",
    categoryColor: "blue",
    ages: "13–18",
    minAge: 13,
    soloStatus: "verified",
    soloNote: "Verified: youth volunteers ages 13–18 are recruited and trained directly by the program. Must maintain a C average.",
    askAbout: false,
    parentRequired: false,
    address: "60 Court Plaza, Asheville, NC 28801",
    lat: 35.5957,
    lng: -82.5500,
    distanceMi: 12,
    phone: "(828) 707-2113",
    email: "jamielee@buncombealternatives.org",
    contactPerson: "Jamie Lee Willocks, Coordinator",
    website: "https://buncombealternatives.org/teen-court/",
    apply: "Application + training; peer attorney needs 5hr extra + bar exam",
    schedule: "Year-round, hearings as scheduled",
    notes: "Must maintain C average. Serve as juror, bailiff, clerk, or peer attorney."
  },
  {
    id: "wnc-young-curator",
    name: "WNC Nature Center — Young Curator",
    tier: 1,
    fit: "Selective semester program, ages 14–18",
    category: "Animals",
    categoryColor: "warning",
    ages: "14–18",
    minAge: 14,
    soloStatus: "verified",
    soloNote: "Verified: program is explicitly for ages 14–18 each fall and spring semester.",
    askAbout: false,
    parentRequired: false,
    address: "75 Gashes Creek Road, Asheville, NC 28805",
    lat: 35.5681,
    lng: -82.4978,
    distanceMi: 14,
    phone: "(828) 259-8080",
    email: null,
    contactPerson: "Lauren Pyle, Youth Volunteer Coordinator",
    website: "https://wncnaturecenter.com/Education/TeenPrograms.html",
    apply: "Application submitted to Youth Volunteer Coordinator",
    schedule: "Fall and Spring semesters",
    notes: "Small competitive cohort; hands-on animal/visitor work."
  },
  {
    id: "wnc-young-naturalist",
    name: "WNC Nature Center — Young Naturalist",
    tier: 1,
    fit: "Larger summer teen program",
    category: "Animals",
    categoryColor: "warning",
    ages: "Teen (range not posted)",
    minAge: null,
    soloStatus: "verify",
    soloNote: "Described as a teen program but the specific age range is not posted on the current site. Call the Nature Center to confirm a 15-year-old can join.",
    askAbout: true,
    parentRequired: false,
    address: "75 Gashes Creek Road, Asheville, NC 28805",
    lat: 35.5681,
    lng: -82.4978,
    distanceMi: 14,
    phone: "(828) 259-8080",
    email: null,
    contactPerson: "Lauren Pyle, Young Naturalist Coordinator",
    website: "https://wildwnc.org/teen-programs/",
    apply: "Contact coordinator for application packet",
    schedule: "Summer-long",
    notes: "Larger, less selective than Young Curator."
  },
  {
    id: "hands-on-asheville",
    name: "Hands On Asheville-Buncombe (portal)",
    tier: 2,
    fit: "Aggregator — new shifts weekly",
    category: "Multi",
    categoryColor: "muted",
    ages: "Varies by listing",
    minAge: null,
    soloStatus: "verify",
    soloNote: "Each listing on the portal has its own age policy — most are 16+ or adult-accompanied. Filter listings and confirm age on each one individually before signing up.",
    askAbout: true,
    parentRequired: false,
    address: "Online portal",
    lat: null,
    lng: null,
    distanceMi: null,
    phone: null,
    email: null,
    website: "https://www.handsonasheville.org/need/",
    apply: "Create account, filter for South Asheville/Arden",
    schedule: "Varies",
    notes: "Most listings 16+ or adult-accompanied, but worth monitoring."
  },
  {
    id: "rant-and-rave",
    name: "RANT and RAVE Book Reviews",
    tier: 3,
    fit: "Remote engagement (not formal service hours)",
    category: "Library",
    categoryColor: "blue",
    ages: "11–18",
    minAge: 11,
    soloStatus: "verified",
    soloNote: "Verified: explicitly open to anyone ages 11–18. Done remotely; no in-person attendance needed.",
    askAbout: false,
    parentRequired: false,
    address: "Remote",
    lat: null,
    lng: null,
    distanceMi: null,
    phone: null,
    email: null,
    website: "https://www.buncombenc.gov/306/For-Teens",
    apply: "Submit reviews online",
    schedule: "On your own time",
    notes: "Can lead to in-branch teen advisory opportunities."
  }
];
